#!/bin/bash
# =============================================================
# setup_network.sh — Start a single-node Besu PoA or QBFT network
# PoA:  Clique, sealer key pre-installed, miner enabled
# QBFT: genesis auto-generated by Besu operator tool
# =============================================================
set -e

BESU_VERSION="24.1.2"
BESU_DIR="/opt/besu"
NETWORK=$1
DATA_DIR="/tmp/besu-${NETWORK}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/../config"

# ── Java ───────────────────────────────────────────────────────────────────────
if ! java -version 2>&1 | grep -qE "version \"(21|22|23)"; then
  echo "Installing Java 21..."
  apt-get install -y openjdk-21-jre-headless -qq > /dev/null 2>&1
fi

# ── Besu ───────────────────────────────────────────────────────────────────────
if [ ! -f "${BESU_DIR}/bin/besu" ]; then
  echo "Downloading Besu ${BESU_VERSION}..."
  mkdir -p "${BESU_DIR}"
  wget -q "https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/${BESU_VERSION}/besu-${BESU_VERSION}.tar.gz" \
       -O /tmp/besu.tar.gz
  tar -xzf /tmp/besu.tar.gz -C "${BESU_DIR}" --strip-components=1
  echo "Besu installed."
fi
export PATH="${BESU_DIR}/bin:$PATH"

# ── Port assignment ────────────────────────────────────────────────────────────
if [ "${NETWORK}" = "poa" ]; then
  RPC_PORT=8545; P2P_PORT=30303
elif [ "${NETWORK}" = "qbft" ]; then
  RPC_PORT=8546; P2P_PORT=30304
else
  echo "Usage: $0 [poa|qbft]"; exit 1
fi

# Kill any stale process on that port
fuser -k ${RPC_PORT}/tcp 2>/dev/null || true
sleep 1

rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}"

# ══════════════════════════════════════════════════════════════════════════════
# PoA (Clique) setup
# Sealer: 0xfe3b557e8fb62b89f4916b721be55ceb828dbd73
# Key:    8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63
# The genesis extraData already encodes this address as the sole signer.
# We write the private key into the data dir so Besu can sign blocks.
# ══════════════════════════════════════════════════════════════════════════════
if [ "${NETWORK}" = "poa" ]; then
  GENESIS_FILE="${CONFIG_DIR}/genesis-poa.json"

  # Install sealer private key — Besu reads this to sign Clique blocks
  echo "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63" \
    > "${DATA_DIR}/key"

  EXTRA_ARGS="--miner-enabled \
    --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
  CONSENSUS_ARGS="--rpc-http-api=ETH,NET,WEB3,CLIQUE,ADMIN,TXPOOL,MINER"

# ══════════════════════════════════════════════════════════════════════════════
# QBFT setup — auto-generate genesis + validator key via Besu operator
# ══════════════════════════════════════════════════════════════════════════════
elif [ "${NETWORK}" = "qbft" ]; then
  EXTRA_ARGS=""
  CONSENSUS_ARGS="--rpc-http-api=ETH,NET,WEB3,QBFT,ADMIN,TXPOOL"
  GEN_DIR="${DATA_DIR}/qbft-gen"
  mkdir -p "${GEN_DIR}"
  GENESIS_FILE="${GEN_DIR}/genesis.json"

  cat > "${GEN_DIR}/qbftConfigFile.json" << 'JSON'
{
  "genesis": {
    "config": {
      "chainId": 1338,
      "berlinBlock": 0,
      "londonBlock": 0,
      "qbft": {
        "blockperiodseconds": 2,
        "epochlength": 30000,
        "requesttimeoutseconds": 4
      }
    },
    "nonce": "0x0",
    "timestamp": "0x58ee40ba",
    "gasLimit": "0xE4E1C0",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "fe3b557e8fb62b89f4916b721be55ceb828dbd73": { "balance": "0xad78ebc5ac6200000" },
      "64a702e6263b7297a96638cac6ae65e6541f4a01": { "balance": "0xad78ebc5ac6200000" }
    }
  },
  "blockchain": {
    "nodes": { "generate": true, "count": 1 }
  }
}
JSON

  echo "Generating QBFT genesis via Besu operator..."
  "${BESU_DIR}/bin/besu" operator generate-blockchain-config \
    --config-file="${GEN_DIR}/qbftConfigFile.json" \
    --to="${GEN_DIR}/networkFiles" \
    --private-key-file-name=key 2>/dev/null

  GENERATED="${GEN_DIR}/networkFiles/genesis.json"
  if [ ! -f "${GENERATED}" ]; then
    echo "ERROR: Besu operator failed to generate QBFT genesis."
    exit 1
  fi

  cp "${GENERATED}" "${GENESIS_FILE}"

  # Install the generated validator key so this node can propose blocks
  NODE_KEY_DIR=$(find "${GEN_DIR}/networkFiles/keys" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)
  if [ -n "${NODE_KEY_DIR}" ]; then
    cp "${NODE_KEY_DIR}/key"     "${DATA_DIR}/key"
    cp "${NODE_KEY_DIR}/key.pub" "${DATA_DIR}/key.pub" 2>/dev/null || true
    echo "Validator key installed."
  else
    echo "WARNING: Could not find generated validator key."
  fi
fi

# ── Launch Besu ────────────────────────────────────────────────────────────────
echo "==> Starting Besu ${NETWORK} on port ${RPC_PORT}..."

nohup "${BESU_DIR}/bin/besu" \
  --genesis-file="${GENESIS_FILE}" \
  --data-path="${DATA_DIR}" \
  --node-private-key-file="${DATA_DIR}/key" \
  --rpc-http-enabled=true \
  --rpc-http-host="0.0.0.0" \
  --rpc-http-port=${RPC_PORT} \
  --rpc-http-cors-origins="*" \
  ${CONSENSUS_ARGS} \
  ${EXTRA_ARGS} \
  --host-allowlist="*" \
  --min-gas-price=0 \
  --p2p-port=${P2P_PORT} \
  --p2p-enabled=false \
  --discovery-enabled=false \
  --logging=WARN \
  > /tmp/besu-${NETWORK}.log 2>&1 &

echo $! > /tmp/besu-${NETWORK}.pid
echo "PID: $(cat /tmp/besu-${NETWORK}.pid)"

# ── Health check ───────────────────────────────────────────────────────────────
echo -n "Waiting for node"
for i in $(seq 1 45); do
  sleep 2
  if curl -sf -X POST -H "Content-Type: application/json" \
     --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
     "http://localhost:${RPC_PORT}" 2>/dev/null | grep -q '"result"'; then
    echo ""
    # Confirm blocks are actually being produced
    sleep 3
    BLOCKNUM=$(curl -sf -X POST -H "Content-Type: application/json" \
      --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
      "http://localhost:${RPC_PORT}" 2>/dev/null | python3 -c "import sys,json; print(int(json.load(sys.stdin)['result'],16))" 2>/dev/null || echo "0")
    echo "Node READY on port ${RPC_PORT} (block #${BLOCKNUM})"
    if [ "${BLOCKNUM}" = "0" ] && [ "${NETWORK}" = "poa" ]; then
      echo "WARNING: Block number still 0 — sealer may not be mining."
      echo "Last 20 log lines:"
      tail -20 /tmp/besu-${NETWORK}.log
    fi
    exit 0
  fi
  echo -n "."
done

echo ""
echo "ERROR: Node failed to start. Last 50 lines:"
tail -50 /tmp/besu-${NETWORK}.log
exit 1
